### ISSUE TITLE
Get File Size

### ISSUE THREAD

**Issue by SeanPrashad** [xerofoify/Python-File-Utils#4]
I'd like to implement a function to get the size of a file in bytes!

**Comment by xerofoify** [comment]
It should work for absolute and relative paths. There are functions for this, just check that it's an absolute path and if not join it together with a complete path. Otherwise works fine.

**Comment by SeanPrashad** [comment]
Update `getFileSize()` to retrieve the absolute path with respect to the current working directory using the `abspath` function ([source](https://stackoverflow.com/questions/51520/how-to-get-an-absolute-file-path-in-python)). Also merged the function into `core.py` for consistency.
